services:
    db:
        image: postgres
        enviroment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "${DB_PORT}:${DB_PORT}"
        env_file:
            - .env

    